[build-system]
requires = [
    "setuptools>=42", 
]
build-backend = "setuptools.build_meta"

[project]
name = "nymph"
#dependencies = [
#    "nymph_bindings @ file:///src/build-ny22py-debug-docker/lib",
#]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["Python"]

[tool.setuptools.dynamic]
version = {file = ["VERSION"]}
