name: Build and Test Nymph

on:
  pull_request:
  push:
    branches: [main, develop]
    tags: ['*']

env:
  Nymph_BUILD_NYMPH_EXE: ON
  Nymph_ENABLE_EXECUTABLES: ON
  Nymph_ENABLE_PYTHON: OFF
  Nymph_ENABLE_TESTING: ON
  Nymph_SINGLETHREADED: OFF

jobs:

  build:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
        python-version: [3.9]

    steps:

      - name: Checkout reposistory
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Mac Dependencies
        if: startsWith(matrix.os, 'macos')  # Mac only
        run: |
          brew update \
          brew install \
            boost

      - name: Linux Dependencies
        if: startsWith(matrix.os, 'ubuntu')  # Linux only
        run: |
          sudo apt-get update
          sudo apt-get install -yq \
            boost

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake -DNymph_BUILD_NYMPH_EXE=${Nymph_BUILD_NYMPH_EXE} -DNymph_ENABLE_EXECUTABLES=${Nymph_ENABLE_EXECUTABLES} -DNymph_ENABLE_PYTHON=${Nymph_ENABLE_PYTHON} -DNymph_ENABLE_TESTING=${Nymph_ENABLE_TESTING} -DNymph_SINGLETHREADED=${Nymph_SINGLETHREADED} ..

      - name: Build
        run: |
          cd build
          make -j install

      - name: Run tests
        run: |
          cd build
          Testing/RunTests

# For debugging
#      - name: Setup tmate session
#        if: ${{ ! success() }}
#        uses: mxschmitt/action-tmate@v3

